name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Hub Image
        run: |
          docker build -t alphadapta/demo .         
          docker push Nasrul0808/alphademoapp
